using System;
using System.Web.Mvc;
using Tables.Properties; // TODO: Sandtrap.Web.Properties

namespace Sandtrap.Web.DataAnnotations
{

    /// <summary>
    /// An attribute used to define the values used to generate a datalist element used to
    /// provide basic auto-complete functionality for a textbox element.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public class DataListAttribute : Attribute, IMetadataAware
    {

        #region .Constructors 

        /// <summary>
        /// Initialises a new instance of DataListAttribute with default properties.
        /// </summary>
        public DataListAttribute()
        {
        }

        /// <summary>
        /// Initialises a new instance of DataListAttribute with specified properties.
        /// </summary>
        /// <param name="dataListProperty">
        /// The name of the property used to generate the option elements.
        /// </param>
        public DataListAttribute(string dataListProperty)
        {
            DataListProperty = dataListProperty;
        }

        #endregion

        #region .Properties 

        /// <summary>
        /// Gets or sets the name of the property used to generate the option elements.
        /// </summary>
        public string DataListProperty { get; set; }

        #endregion

        #region .Methods 

        /// <summary>
        /// Adds additional metadata values used in rendering tables generated by the 
        /// <see cref="Sandtrap.Web.Html.TableHelper.TableEditorFor"/> method.
        /// </summary>
        /// <param name="metadata">
        /// The metadata.
        /// </param>
        public void OnMetadataCreated(ModelMetadata metadata)
        {
            // Add metadata
            metadata.AdditionalValues[Resources.DataListAttribute_DataListProperty] = DataListProperty;
        }

        #endregion

    }
}
