//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandtrap.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sandtrap.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} used to define a datalist does not implement IEnumerable&lt;string&gt;..
        /// </summary>
        public static string DataListAttribute__InvalidDataList {
            get {
                return ResourceManager.GetString("DataListAttribute__InvalidDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataListProperty.
        /// </summary>
        public static string DataListAttribute_DataListProperty {
            get {
                return ResourceManager.GetString("DataListAttribute_DataListProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} used to define a datalist is an empty collection.
        /// </summary>
        public static string DataListAttribute_EmptyDataList {
            get {
                return ResourceManager.GetString("DataListAttribute_EmptyDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model in the view does not contain a property for a DataList named {0}.
        /// </summary>
        public static string DataListAttribute_MissingDataList {
            get {
                return ResourceManager.GetString("DataListAttribute_MissingDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataList for property {0} cannot be null..
        /// </summary>
        public static string DataListAttribute_NullDataList {
            get {
                return ResourceManager.GetString("DataListAttribute_NullDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} used to define a SelectList does not implement IEnumerable&lt;SelectListItem&gt;..
        /// </summary>
        public static string DropDownListAttribute__InvalidSelectList {
            get {
                return ResourceManager.GetString("DropDownListAttribute__InvalidSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} used to define a SelectList is an empty collection.
        /// </summary>
        public static string DropDownListAttribute_EmptySelectList {
            get {
                return ResourceManager.GetString("DropDownListAttribute_EmptySelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model in the view does not contain a property for a SelectList named {0}.
        /// </summary>
        public static string DropDownListAttribute_MissingSelectList {
            get {
                return ResourceManager.GetString("DropDownListAttribute_MissingSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SelectList for property {0} cannot be null..
        /// </summary>
        public static string DropDownListAttribute_NullSelectList {
            get {
                return ResourceManager.GetString("DropDownListAttribute_NullSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectListOptionLabel.
        /// </summary>
        public static string DropDownListAttribute_OptionLabel {
            get {
                return ResourceManager.GetString("DropDownListAttribute_OptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectListProperty.
        /// </summary>
        public static string DropDownListAttribute_SelectListProperty {
            get {
                return ResourceManager.GetString("DropDownListAttribute_SelectListProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model cannot be IDictionary&lt;TKey, TValue&gt; or IEnumerable&lt;IGrouping&lt;TKey, TValue&gt;&gt; or ILookup&lt;TKey, TValue&gt;.
        /// </summary>
        public static string Table_GroupedCollection {
            get {
                return ResourceManager.GetString("Table_GroupedCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type in the collection does not have a parameterless constructor.
        /// </summary>
        public static string Table_NoTypeConstructor {
            get {
                return ResourceManager.GetString("Table_NoTypeConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model cannot be null.
        /// </summary>
        public static string Table_NullCollection {
            get {
                return ResourceManager.GetString("Table_NullCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type in the collection could not be resolved.
        /// </summary>
        public static string Table_UnresolvedType {
            get {
                return ResourceManager.GetString("Table_UnresolvedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableColumnDisplayProperty.
        /// </summary>
        public static string TableColumnAttribute_DisplayProperty {
            get {
                return ResourceManager.GetString("TableColumnAttribute_DisplayProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableColumnExclude.
        /// </summary>
        public static string TableColumnAttribute_Exclude {
            get {
                return ResourceManager.GetString("TableColumnAttribute_Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableColumnIDProperty.
        /// </summary>
        public static string TableColumnAttribute_IDProperty {
            get {
                return ResourceManager.GetString("TableColumnAttribute_IDProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableColumnIncludeTotal.
        /// </summary>
        public static string TableColumnAttribute_IncludeTotal {
            get {
                return ResourceManager.GetString("TableColumnAttribute_IncludeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class definition &apos;{0}&apos; does not contain a public property named &apos;{1}&apos;.
        /// </summary>
        public static string TableColumnAttribute_InvalidProperty {
            get {
                return ResourceManager.GetString("TableColumnAttribute_InvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableColumnNoRepeat.
        /// </summary>
        public static string TableColumnAttribute_NoRepeat {
            get {
                return ResourceManager.GetString("TableColumnAttribute_NoRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableColumnReadonly.
        /// </summary>
        public static string TableColumnAttribute_Readonly {
            get {
                return ResourceManager.GetString("TableColumnAttribute_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableControllerName.
        /// </summary>
        public static string TableDisplayAttribute_ControllerName {
            get {
                return ResourceManager.GetString("TableDisplayAttribute_ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableDetailsActionName.
        /// </summary>
        public static string TableDisplayAttribute_DetailsActionName {
            get {
                return ResourceManager.GetString("TableDisplayAttribute_DetailsActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableEditActionName.
        /// </summary>
        public static string TableDisplayAttribute_EditActionName {
            get {
                return ResourceManager.GetString("TableDisplayAttribute_EditActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncludeDetailsLink.
        /// </summary>
        public static string TableDisplayAttribute_IncludeDetailsLink {
            get {
                return ResourceManager.GetString("TableDisplayAttribute_IncludeDetailsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncludeEditLink.
        /// </summary>
        public static string TableDisplayAttribute_IncludeEditLink {
            get {
                return ResourceManager.GetString("TableDisplayAttribute_IncludeEditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncludeRowNumbers.
        /// </summary>
        public static string TableDisplayAttribute_IncludeRowNumbers {
            get {
                return ResourceManager.GetString("TableDisplayAttribute_IncludeRowNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class definition &apos;{0}&apos; does not contain a public property named &apos;{1}&apos;.
        /// </summary>
        public static string TableDisplayAttribute_InvalidProperty {
            get {
                return ResourceManager.GetString("TableDisplayAttribute_InvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller cannot be null.
        /// </summary>
        public static string TableDisplayAttribute_NullController {
            get {
                return ResourceManager.GetString("TableDisplayAttribute_NullController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableRouteValue.
        /// </summary>
        public static string TableDisplayAttribute_RouteValue {
            get {
                return ResourceManager.GetString("TableDisplayAttribute_RouteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableEditAllowAdditions.
        /// </summary>
        public static string TableEditAttribute_AllowAdditions {
            get {
                return ResourceManager.GetString("TableEditAttribute_AllowAdditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableEditAllowDeletions.
        /// </summary>
        public static string TableEditAttribute_AllowDeletions {
            get {
                return ResourceManager.GetString("TableEditAttribute_AllowDeletions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class definition &apos;{0}&apos; does not contain a public property named &apos;{1}&apos;.
        /// </summary>
        public static string TableEditAttribute_InvalidProperty {
            get {
                return ResourceManager.GetString("TableEditAttribute_InvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableEditActiveProperty.
        /// </summary>
        public static string TableEditAttribute_IsActiveProperty {
            get {
                return ResourceManager.GetString("TableEditAttribute_IsActiveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableEditDirtyProperty.
        /// </summary>
        public static string TableEditAttribute_IsDirtyProperty {
            get {
                return ResourceManager.GetString("TableEditAttribute_IsDirtyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is not a boolean.
        /// </summary>
        public static string TableEditAttribute_NotBool {
            get {
                return ResourceManager.GetString("TableEditAttribute_NotBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableLinkActionName.
        /// </summary>
        public static string TableLinkAttribute_ActionName {
            get {
                return ResourceManager.GetString("TableLinkAttribute_ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableLinkControllerName.
        /// </summary>
        public static string TableLinkAttribute_ControllerName {
            get {
                return ResourceManager.GetString("TableLinkAttribute_ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableLinkDisplayProperty.
        /// </summary>
        public static string TableLinkAttribute_DisplayProperty {
            get {
                return ResourceManager.GetString("TableLinkAttribute_DisplayProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableLinkInclude.
        /// </summary>
        public static string TableLinkAttribute_IncludeLink {
            get {
                return ResourceManager.GetString("TableLinkAttribute_IncludeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class definition &apos;{0}&apos; does not contain a public property named &apos;{1}&apos;.
        /// </summary>
        public static string TableLinkAttribute_InvalidProperty {
            get {
                return ResourceManager.GetString("TableLinkAttribute_InvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller cannot be null.
        /// </summary>
        public static string TableLinkAttribute_NullController {
            get {
                return ResourceManager.GetString("TableLinkAttribute_NullController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableLinkRouteValue.
        /// </summary>
        public static string TableLinkAttribute_RouteValue {
            get {
                return ResourceManager.GetString("TableLinkAttribute_RouteValue", resourceCulture);
            }
        }
    }
}
